---
- name: Kafka Listening Rulebook
  hosts: all
  sources:
    - eda.builtin.kafka:
        bootstrap_servers: "localhost:9092"
        topics:
          - "my-topic"
  rules:
    - name: DEBUG - Print any event that arrives
      condition: true
      action:
        run_job_template:
          name: "Demo Job Template"
          organization: "Default"
        ansible.builtin.debug:
          msg: "Event received: {{ event }}"
