- name: Poll for new records in ServiceNow
  hosts: all
  sources:
    - name: my_snow
      servicenow.itsm.records:
        table: incident
        interval: 10
        sysparm_query: "state=2^priority=4"
        timestamp_field: "sys_updated_on"
      
  rules:
    - name: Trigger Job Template
      condition: event.payload.incident_number is defined
      action:
        run_job_template:
          name: "Close-Incident-Template"
          organization: "Default"
          job_args:
            extra_vars:
              incident_id: "{{ event.payload.incident_number }}"