---
- name: ServiceNOW Events
  hosts: all
  execution_strategy: parallel
  sources:
    - ansible.eda.webhook:
        port: "{{ webhook_port | default(5000) }}"
        token: "{{ webhook_token | default(omit) }}"
  rules:
    - name: ServiceNOW | Provision Virtual Machine
      condition: |
        event.payload.event == "SERVICE_CATALOG"
      action:
        run_job_template:
          name: Demo-Cleiton-Template
          organization: Default
       

    - name: ServiceNOW | Unhandled Events
      condition: event.payload is defined
      action:
        debug: